size(500, 600);
println("start of console");
String[] fontList = PFont.list();
printArray(fontList);
int titleX, titleY, titleWidth, titleHeight;
titleX = width*1/5;
titleY = height*1/10;
titleWidth = width*3/5;
titleHeight = height*1/10;
String title = "Wahoo!";
color purpleInk = #88007D;
color nightModeGreenInk = #04B200;
color resetColor = #000000;
fill(purpleInk);
textAlign(CENTER, CENTER);
textFont(titleFont, 55);
text();
fill(resetColor);
